### ISSUE TITLE
crashing on yunohost 12.0.7

### ISSUE THREAD

**Issue by Salpertio** [YunoHost-Apps/headplane_ynh#11]
its strange since i thought that just changing the port from the default that yunohost gives "3000" would fix the issue but keep walking into an nginx 502

Nov 29 04:15:21 node[89127]: }
Nov 29 04:15:21 node[89127]: Node.js v22.11.0
Nov 29 04:15:21 systemd[1]: headplane.service: Main process exited, code=exited, status=1/FAILURE
Nov 29 04:15:21 systemd[1]: headplane.service: Failed with result 'exit-code'.
Nov 29 04:15:21 systemd[1]: headplane.service: Consumed 2.060s CPU time.
Nov 29 04:15:21 systemd[1]: headplane.service: Scheduled restart job, restart counter is at 9.
Nov 29 04:15:21 systemd[1]: Stopped headplane.service - Headplane: Headscale Management Web UI.
Nov 29 04:15:21 systemd[1]: headplane.service: Consumed 2.060s CPU time.
Nov 29 04:15:21 systemd[1]: Started headplane.service - Headplane: Headscale Management Web UI.
Nov 29 04:15:21 node[89140]: 2024-11-29T04:15:21.981Z (INFO) [SRVX] Running with Node.js 22.11.0
Nov 29 04:15:21 node[89140]: 2024-11-29T04:15:21.983Z (INFO) [SRVX] Found node_modules dependencies
Nov 29 04:15:21 node[89140]: 2024-11-29T04:15:21.983Z (INFO) [SRVX] Found build directory
Nov 29 04:15:23 node[89140]: 2024-11-29T04:15:23.471Z (INFO) [CTXT] Loading environment variables from .env
Nov 29 04:15:23 node[89140]: (node:89140) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
Nov 29 04:15:23 node[89140]: (Use `node --trace-deprecation ...` to show where the warning was created)
Nov 29 04:15:23 node[89140]: 2024-11-29T04:15:23.476Z (INFO) [INTG] Loading integration: proc
Nov 29 04:15:23 node[89140]: 2024-11-29T04:15:23.478Z (ERRO) [INTG] Could not find Headscale process
Nov 29 04:15:23 node[89140]: 2024-11-29T04:15:23.478Z (ERRO) [INTG] Integration proc is not available
Nov 29 04:15:23 node[89140]: 2024-11-29T04:15:23.478Z (INFO) [CTXT] Starting Headplane with Context
Nov 29 04:15:23 node[89140]: 2024-11-29T04:15:23.478Z (INFO) [CTXT] HEADSCALE_URL: #redacted
Nov 29 04:15:23 node[89140]: 2024-11-29T04:15:23.479Z (INFO) [CTXT] Integration: None
Nov 29 04:15:23 node[89140]: 2024-11-29T04:15:23.479Z (INFO) [CTXT] Config: Unavailable
Nov 29 04:15:23 node[89140]: 2024-11-29T04:15:23.479Z (INFO) [CTXT] OIDC: Unavailable
Nov 29 04:15:23 node[89140]: node:events:496
Nov 29 04:15:23 node[89140]:       throw er; // Unhandled 'error' event
Nov 29 04:15:23 node[89140]:       ^
Nov 29 04:15:23 node[89140]: Error: listen EADDRINUSE: address already in use 0.0.0.0:3000
Nov 29 04:15:23 node[89140]:     at Server.setupListenHandle [as _listen2] (node:net:1907:16)
Nov 29 04:15:23 node[89140]:     at listenInCluster (node:net:1964:12)
Nov 29 04:15:23 node[89140]:     at node:net:2170:7
Nov 29 04:15:23 node[89140]:     at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
Nov 29 04:15:23 node[89140]: Emitted 'error' event on Server instance at:
Nov 29 04:15:23 node[89140]:     at emitErrorNT (node:net:1943:8)
Nov 29 04:15:23 node[89140]:     at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
Nov 29 04:15:23 node[89140]:   code: 'EADDRINUSE',
Nov 29 04:15:23 node[89140]:   errno: -98,
Nov 29 04:15:23 node[89140]:   syscall: 'listen',
Nov 29 04:15:23 node[89140]:   address: '0.0.0.0',
Nov 29 04:15:23 node[89140]:   port: 3000
Nov 29 04:15:23 node[89140]: }
Nov 29 04:15:23 node[89140]: Node.js v22.11.0
Nov 29 04:15:23 systemd[1]: headplane.service: Main process exited, code=exited, status=1/FAILURE
Nov 29 04:15:23 systemd[1]: headplane.service: Failed with result 'exit-code'.
Nov 29 04:15:23 systemd[1]: headplane.service: Consumed 1.975s CPU time.
Nov 29 04:15:23 systemd[1]: headplane.service: Scheduled restart job, restart counter is at 10.
Nov 29 04:15:23 systemd[1]: Stopped headplane.service - Headplane: Headscale Management Web UI.
Nov 29 04:15:23 systemd[1]: headplane.service: Consumed 1.975s CPU time.
Nov 29 04:15:23 systemd[1]: headplane.service: Start request repeated too quickly.
Nov 29 04:15:23 systemd[1]: headplane.service: Failed with result 'exit-code'.
Nov 29 04:15:23 systemd[1]: Failed to start headplane.service - Headplane: Headscale Management Web UI.

**Comment by mdtita** [comment]
fixed in #12
